set_property SRC_FILE_INFO {cfile:/home/mike/repos/fpga-guitar/cons/cons.xdc rfile:../../../../cons/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M9 IOSTANDARD LVCMOS33} [get_ports clock]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {LED[0]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {LED[1]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports {LED[2]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {LED[3]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports mclk1]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports ws1]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports sclk1]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports sd_tx]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports mclk0]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports ws0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports sclk0]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports sd_rx]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports sw]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A2 IOSTANDARD LVCMOS33} [get_ports A]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports B]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 3 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list theBlockDesign_i/i2s_transceiver_0/mclk]]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 23 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[0]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[1]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[2]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[3]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[4]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[5]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[6]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[7]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[8]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[9]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[10]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[11]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[12]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[13]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[14]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[15]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[16]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[17]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[18]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[19]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[20]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[21]} {theBlockDesign_i/i2s_transceiver_0/U0/l_data_tx_int[22]}]]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 3 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list theBlockDesign_i/i2s_transceiver_0/U0/mclk]]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[0]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[1]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[2]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[3]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[4]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[5]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[6]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[7]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[8]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[9]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[10]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[11]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[12]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[13]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[14]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[15]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[16]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[17]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[18]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[19]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[20]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[21]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[22]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[23]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[24]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[25]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[26]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[27]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[28]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[29]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[30]} {theBlockDesign_i/i2s_transceiver_0/U0/ws_cnt_reg[31]}]]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clock_IBUF]
