# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/mike/repos/fpga-guitar/cons/cons.xdc

# Block Designs: /home/mike/repos/fpga-guitar/ip/theBlockDesign/theBlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==theBlockDesign || ORIG_REF_NAME==theBlockDesign} -quiet] -quiet

# IP: /home/mike/repos/fpga-guitar/ip/theBlockDesign/ip/theBlockDesign_xlconstant_0_0/theBlockDesign_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==theBlockDesign_xlconstant_0_0 || ORIG_REF_NAME==theBlockDesign_xlconstant_0_0} -quiet] -quiet

# IP: /home/mike/repos/fpga-guitar/ip/theBlockDesign/ip/theBlockDesign_i2s_transceiver_0_0/theBlockDesign_i2s_transceiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==theBlockDesign_i2s_transceiver_0_0 || ORIG_REF_NAME==theBlockDesign_i2s_transceiver_0_0} -quiet] -quiet

# IP: /home/mike/repos/fpga-guitar/ip/theBlockDesign/ip/theBlockDesign_rotary_encoder_0_0/theBlockDesign_rotary_encoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==theBlockDesign_rotary_encoder_0_0 || ORIG_REF_NAME==theBlockDesign_rotary_encoder_0_0} -quiet] -quiet

# IP: /home/mike/repos/fpga-guitar/ip/theBlockDesign/ip/theBlockDesign_word_receive_0_0/theBlockDesign_word_receive_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==theBlockDesign_word_receive_0_0 || ORIG_REF_NAME==theBlockDesign_word_receive_0_0} -quiet] -quiet

# IP: /home/mike/repos/fpga-guitar/ip/theBlockDesign/ip/theBlockDesign_xlconstant_1_0/theBlockDesign_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==theBlockDesign_xlconstant_1_0 || ORIG_REF_NAME==theBlockDesign_xlconstant_1_0} -quiet] -quiet

# XDC: /home/mike/repos/fpga-guitar/ip/theBlockDesign/theBlockDesign_ooc.xdc
